#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_api_docs.py — machine-generated API reference for the adaptive_amr
stack. Walks every Python module under src/adaptive_amr/<pkg>/src and extracts
module / class / function docstrings with AST (no imports executed), writing a
consolidated Markdown reference to docs/api_reference.md.

Usage:
    python3 scripts/docs/generate_api_docs.py [--output docs/api_reference.md]
"""

import argparse
import ast
import os
import sys


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC_DIR = os.path.join(ROOT, "src", "adaptive_amr")


def clean_doc(doc: str) -> str:
    """Docstring -> single-paragraph markdown text."""
    if not doc:
        return ""
    lines = [ln.rstrip() for ln in doc.strip().splitlines()]
    return "\n".join(lines)


def render_module(path: str) -> str:
    """Render one python module file as a markdown section."""
    with open(path, "r") as handle:
        tree = ast.parse(handle.read(), filename=path)

    rel = os.path.relpath(path, ROOT)
    out = ["\n### `{}`".format(rel), ""]

    module_doc = ast.get_docstring(tree)
    if module_doc:
        out.append(clean_doc(module_doc))
        out.append("")

    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            doc = ast.get_docstring(node)
            out.append("#### `class {}`".format(node.name))
            if doc:
                out.append(clean_doc(doc))
            out.append("")
            for item in node.body:
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    fn_doc = ast.get_docstring(item)
                    out.append("- `{}()`{}".format(
                        item.name,
                        " — {}".format(fn_doc.splitlines()[0]) if fn_doc else ""))
            out.append("")
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith("_"):
                continue
            doc = ast.get_docstring(node)
            out.append("#### `{}()`".format(node.name))
            if doc:
                out.append(clean_doc(doc))
            out.append("")
    return "\n".join(out)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate the API reference")
    parser.add_argument("--output", default=os.path.join(ROOT, "docs",
                                                         "api_reference.md"))
    args = parser.parse_args(argv)

    sections = []
    # real packages only: directories that contain a package.xml
    packages = sorted(
        d for d in os.listdir(SRC_DIR)
        if os.path.isfile(os.path.join(SRC_DIR, d, "package.xml")))
    for pkg in packages:
        pkg_parts = ["\n## {}\n".format(pkg)]
        # pure algorithm cores live in src/<pkg>; driver packages keep their
        # logic in scripts/ — cover both so every package is documented.
        module_root = os.path.join(SRC_DIR, pkg, "src", pkg)
        scripts_dir = os.path.join(SRC_DIR, pkg, "scripts")
        if os.path.isdir(module_root):
            for dirpath, _, filenames in os.walk(module_root):
                for name in sorted(filenames):
                    if name.endswith(".py") and name != "__init__.py":
                        pkg_parts.append(render_module(os.path.join(dirpath, name)))
        elif os.path.isdir(scripts_dir):
            for name in sorted(os.listdir(scripts_dir)):
                if name.endswith(".py"):
                    pkg_parts.append(render_module(os.path.join(scripts_dir, name)))
        sections.append("\n".join(pkg_parts))

    header = (
        "# kittiraith_ws — API Reference\n\n"
        "> Machine-generated by `scripts/docs/generate_api_docs.py`. "
        "Re-run the script after any API change:\n>\n"
        "> ```bash\n> python3 scripts/docs/generate_api_docs.py\n> ```\n"
        ">\n> This reference covers the 39 importable Python modules "
        "(the pure algorithm cores). ROS node interfaces (topics, services, "
        "parameters) are documented per package in each module's README "
        "(see `docs/MODULE_REFERENCE.md`).\n"
    )
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w") as handle:
        handle.write(header)
        handle.write("\n".join(sections))
    print("Wrote {} ({} packages)".format(args.output, len(packages)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
